name: baghdad-ai-summit
region: nyc
services:
- name: web
  github:
    repo: mohammadNafia/ai---fest-
    branch: main
    deploy_on_push: true
  source_dir: /
  http_port: 8080
  build_command: npm run build
  run_command: npm run start
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
